### ISSUE TITLE
Can't figure out plugin

### ISSUE THREAD

**Issue by Marco-Daniel** [graysonhicks/gatsby-plugin-remote-images#10]
Hi,

I'm trying to build a simple portfolio website using gatsby and kentico cloud. I'm trying to use your plugin to get the images to work with gatsby-image, but for some reason it won't create local files to use. Maybe i'm doing something wrong but I just can't figure out how to get this working.
For some reason it's not creating the localImage.

`{
      resolve: `gatsby-plugin-remote-images`,
      options: {
        nodeType: 'kenticoCloudItemLogo',
        imagePath: 'url',
        name: 'localImage',
      }`

This is how i've set up the plugin.

`query MyQuery {
  allKenticoCloudItemLogo {
    nodes {
      elements {
        logo {
          assets {
            url
          }
        }
      }
    }
  }
}`
This is the 'normal' query (which will return a absolute img path). In the GraphiQL tool the localImage node isn't created and running the query from within gatsby will also result in an error.

'query logoQuery {
            kenticoCloudItemLogo {
                elements {
                  logo {
                    assets {
                       localImage {
                           childImageSharp {
                               fluid(maxwidth: 120) {
                                   ...GatsbyImageSharpFluid
                               }
                           }
                       }                    
                    }
                  }
                }
              }  
        }'

This is the query i'm using inside of gatsby. 

Really hope you can help. Thanks in advance!

**Comment by graysonhicks** [comment]
Hi Marco-Daniel!  Do you a repo that you can link to for debugging?

**Comment by Marco-Daniel** [comment]
Hi graysonhicks! Thanks for the reply. I already moved on to use Netlify CMS so I no longer need the plugin. But you can see the sourcecode i used for kentico here: https://github.com/Marco-Daniel/kenticoCloud
I would like to be able to use kentico in the future again so it would be nice to know what I did wrong :)

**Comment by graysonhicks** [comment]
Thanks for the update @Marco-Daniel!  I'll give that repo a try when I get a chance.
