### ISSUE TITLE
Specify alternate field to map nodes to

### ISSUE THREAD

**Issue by jdesherlia** [graysonhicks/gatsby-plugin-remote-images#11]
I am trying to use this plugin to create gatsby-image compatible local nodes from data sourced via [gatsby-source-apiserver](https://www.gatsbyjs.org/packages/gatsby-source-apiserver/?=api). It seems to work fine on initial load, however on subsequent loads it fails due to the fact that gatsby-source-apiserver generates unique IDs and puts the response's id field into a field called `alternative_id`.

It would be pretty helpful to be able to specify in the plugin definition, the field that we prefer to use for [mapping nodes](https://github.com/graysonhicks/gatsby-plugin-remote-images/blob/53b590a0d21e7fdfa5946e76bf081f3d9102b1c7/src/gatsby-node.js#L43). ie this:

```
node[`${name}___NODE`] = fileNode.id
```

would become this:

```
const linkedField = 'alternate_id'
node[`${name}___NODE___${linkedField}`] = `fileNode.${linkedField}`
```

At least, I think thats how it would go. Found a reference to it [here](https://www.gatsbyjs.org/docs/schema-gql-type#foreign-key-reference-___node)

Thoughts?

-Josh-

**Comment by jdesherlia** [comment]
I submitted a [pr](#12) that should resolve this. Tested locally and it looks good, and the default setting should make the PR non-breaking.

**Comment by jdesherlia** [comment]
Scratch that, my PR didn't solve the issue. Will keep digging...

**Comment by jdesherlia** [comment]
I'm closing this. I don't think there is a clean way to do this, and to be honest the problem is more that gatsby-plugin-apiserver creates unique IDs on each run using nanoid. Resolved by writing my own importer in gatsby-node.

**Comment by stephanebruckert** [comment]
I would need this too, is there any solution for it today? Thx
