### ISSUE TITLE
"Type" validation

### ISSUE THREAD

**Issue by Snak3dks** [graysonhicks/gatsby-plugin-remote-images#149]
After changes in 3.6.0 I cannot run the plugin anymore.

` ERROR #11331  API.NODE.VALIDATION

Invalid plugin options for "gatsby-plugin-remote-images":

- "type" must be of type object
`

I can see in commits that "type" attribute in options requires an object instead of string now, but docs are not updated, I can still find 
`"type": "array"` in README. Please, fix docs or the attribute validation.

**Comment by linoxyn** [comment]
@Snak3dks this worked for me. I edited  .node_modules\gatsby-plugin-remote-images\gatsby-node.js  

line 22 - from:
`
   type: Joi.object(),
`
to:
`
   type: Joi.string(),
`

**Comment by Snak3dks** [comment]
@linoxyn that's clear, but it would be good if author fix this in the library directly. I don't want to make a fork.

**Comment by graysonhicks** [comment]
Thanks, I can get this updated!

**Comment by graysonhicks** [comment]
Just published fix in `3.6.6`, let me know if it is still a problem, thanks!

**Comment by linoxyn** [comment]
@graysonhicks thank you very much for the update. Works! I've made a recent choice and moved away from a nice though complex, more than I needed, Gatsbyjs source plugin to two easier to manage and have a more straight forward way to get data into my projects - this plugin works great to coordinate and source images from Firestore collections dB with Firebase Storage... I'm happy! 👍🏻
