### ISSUE TITLE
Multiple remote images

### ISSUE THREAD

**Issue by dtbaker** [graysonhicks/gatsby-plugin-remote-images#2]
Hey there,

Just playing around with this plugin :ok_hand: 

It wasn't entirely clear how to have multiple remote images? Do the options handle arrays of values or does gatsby support multiple `{ resolve...}` entries in the config file?

Thanks heaps!
Dave

**Comment by raquelmsmith** [comment]
In another issue, Kyle says you can use multiple instances of a plugin in the gatsby-config file: https://github.com/gatsbyjs/gatsby/issues/2021

I haven't tried this myself, but it's worth looking into.

**Comment by graysonhicks** [comment]
Hi @dtbaker sorry I am just looking at this.  At the moment it only takes one `imagePath` option as a string, but I can certainly look at allowing an array there.  For now, multiple instances of the plugin would work.

**Comment by dtbaker** [comment]
Hey thanks for the reply.

I ended up writing my own plugin to handle different remote images.

Something along the lines of:

```
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)
const get = require('lodash/get')

exports.onCreateNode = async ({ node, actions, store, cache, createNodeId }, options) => {
  const { createNode } = actions
  const { auth = {}, ext = null } = options

  let fileNode
  if (node.internal.type === 'Airtable') {
    try {
      if (node.table === 'Contributors' && node.data.Published) {
        const fileNodeHero = await createRemoteFileNode({
          url: get(node, 'data.Hero_Image[0].url'),
          store,
          cache,
          createNode,
          createNodeId,
          auth,
          ext,
        })
        if (fileNodeHero) {
          const keyName = 'heroImage'
          node[`${keyName}___NODE`] = fileNodeHero.id
        }

        const fileNodeAvatar = await createRemoteFileNode({
          url: get(node, 'data.Avatar_Image[0].url'),
          store,
          cache,
          createNode,
          createNodeId,
          auth,
          ext,
        })
        if (fileNodeAvatar) {
          node.avatarImage___NODE = fileNodeAvatar.id
        }
      } else if (node.ta....
```
