### ISSUE TITLE
Problem resolving fixed image

### ISSUE THREAD

**Issue by wyzzy** [graysonhicks/gatsby-plugin-remote-images#24]
I have set up this plug-in to create a `localImage` property of an entity in our model. At site build time, it looks like the url reference to the remote image is successfully being used to create a remote file node.

However when I try to use the image with the Gatsby `Img` component, I'm getting an error because `childImageSharp` is null. In the fragment below, `logoImg` has been assigned the value from `localImage`, retrieved using the following query.

```
query {
  allThings {
    edges{
      node {
        localImage {
          childImageSharp {
            fixed(height: 30, width: 30, quality: 100) {
              ...GatsbyImageSharpFixed
            }
          }
        }
      }
    }
  }
}
```

This is the error.
```
TypeError: null is not an object (evaluating 'logoImg.childImageSharp.fixed')
renderImg
src/components/ListItem.tsx:21
  18 | const ListItem: React.FunctionComponent<Props> = ({ logoUrl, text, percentage, logoImg }) => {
  19 |   const renderImg = (): JSX.Element => {
  20 |     if (logoImg) {
> 21 |       return <Img fixed={logoImg.childImageSharp.fixed} />
  22 |     }
  23 |     return <Image src={logoUrl} alt={text} onError={imageBackup} />
```

and the relevant section of the `gatsby-config.js` is:

```
{
      resolve: `gatsby-plugin-remote-images`,
      options: {
        nodeType: 'Thing',
        imagePath: 'iconSrc.url',
      },
},
``` 

Points that may be relevant:

- Listing all the `Things` in GraphiQL shows non-null values for the `localImage` property for every Thing that has a valid `iconSrc.url` value and was apparently successfully resolved by the remote file node creation process.

- Listing all the `allImageSharp` nodes none of the image nodes created by the remote image plugin are listed, while all those for local files are.

It feels SO close to working. Any pointers would be most welcome.

**Comment by graysonhicks** [comment]
Hey @wyzzy!  Do you have a repo or codepen that I can have a look at?  When you look at the `Things` in GraphiQL, some do have `null` for `localImage`?

**Comment by graysonhicks** [comment]
Closing due to lack of repo for testing.
