### ISSUE TITLE
gatsby-source-graphql issue seems fixed

### ISSUE THREAD

**Issue by jwxz** [graysonhicks/gatsby-plugin-remote-images#25]
Sorry, I'm not sure if I am missing something but it looks like the issue about gatsby-source-graphql referenced in the readme has been fixed:

https://www.gatsbyjs.org/docs/schema-customization/#feeding-remote-images-into-gatsby-image

I'm still kind of new to gatsby. I'll try and help if I can.

**Comment by graysonhicks** [comment]
Yes see other issue #7
