### ISSUE TITLE
Random failing RequestError: getaddrinfo ENOTFOUND with 443

### ISSUE THREAD

**Issue by Jsalvat** [graysonhicks/gatsby-plugin-remote-images#27]
We have more than 3000+ images on our website. When we do a development from localhost sometimes fails with this errors:

gatsby-plugin-remote-images ERROR: failed to process https://s3-eu- .....etc
RequestError: getaddrinfo ENOTFOUND s3...amazonaws.com:443

That image that fails is completly accessible (we've tested it) but it keeps failing randomly.

Sometimes it's one image and sometimes it's another image.

It's just appearing this error on localhost, not "online"

Any clue?

btw, we use iOS

**Comment by graysonhicks** [comment]
Do you have link to a repo so I can replicate?
