### ISSUE TITLE
Invariant Violation Error

### ISSUE THREAD

**Issue by roylines** [graysonhicks/gatsby-plugin-remote-images#3]
Plugin fails for second run when loading from the cache with the following error:

> Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: `localImage___  NODE`. There is no corresponding node with the `id` field matching

This is due to missing parentNodeId parameter on call to createRemoteFileNode.

Pull request with fix is incoming...

**Comment by roylines** [comment]
Added fix in https://github.com/graysonhicks/gatsby-plugin-remote-images/pull/4. Would be great if you could prioritise this please.

**Comment by YoranBrondsema** [comment]
Same, seeing the issue too!
