### ISSUE TITLE
Impossible to add two image fields in the same node

### ISSUE THREAD

**Issue by kilburn** [graysonhicks/gatsby-plugin-remote-images#33]
In one of our projects we have a few nodes that (because reasons) have more than one field containing a remote image. The `gatsby-config.js` contains something like:

```
    {
      resolve: 'gatsby-plugin-remote-images',
      options: {
        nodeType: 'someNodeType',
        imagePath: 'introImage',
        name: 'localIntroImage',
      },
    },
    {
      resolve: 'gatsby-plugin-remote-images',
      options: {
        nodeType: 'someNodeType',
        imagePath: 'bodyImage',
        name: 'localBodyImage',
      },
    },
```
This setup worked fine until we updated to the latest (`2.0.0`) version. With the newer version there are no visible errors, but both the `localIntroImage` and `localBodyImage` in the `someNodeType` end up pointing to the same `FileNode` instance.

This happens because the plugin is storing a mapping `sourceNodeId -> generatedFileNodeId` in the `fileNodeMap` map. Obviously, this means that even though the plugin generates two different `FileNode`s with the proper downloaded files, the `createResolvers` api always returns whatever `FileNode` happened to have been generated last.

We temporarily solved this by using a custom version of the plugin where the keys in `fileNodeMap` are `${node.id}-${name}` instead of just `${node.id}`.

**Comment by graysonhicks** [comment]
Thanks @kilburn !  @wKovacs64 looks like that map ID needs to be updated.  Does their fix look like it should be adopted overall?

**Comment by wKovacs64** [comment]
Can you check out the fix in #34? I think that should restore this functionality.

**Comment by kilburn** [comment]
I haven't tried it yet but looking at the code it should solve it.

However, I've found another issue with the `fileNodeMap` approach: the map is empty on subsequent gatsby build/develop runs unless you remove the cache.

I've created a test project here: [https://github.com/kilburn/gatsby-plugin-remote-images-demo](https://github.com/kilburn/gatsby-plugin-remote-images-demo) that demonstrates both issues at the same time.

The newfound problem is that if you run `gatsby develop`, let it finish, then stop it, and run `gatsby develop` again, you will see that the images seem to "not be downloaded" that second time. However, if  you remove the `.cache` folder and run again then it will work again.

This happens because the original nodes haven't changed. Hence, `gatsby` skips calling the `onCreateNode` api for them, and the `FileNode`s never get populated in the `fileNodeMap` map. I think that removing the `fileNodeMap` thing and using gatsby's `cache` helper would solve this problem, but I have not time to try it right now.

I will reply here when I find the time to do some more tests.

**Comment by wKovacs64** [comment]
Hm, I had several people test persisting through cached builds when #30 went in, but maybe we were all using a node type that got created every build, regardless of cache (or something)? For example, subsequent rebuilds work if the `nodeType` is `Site` (without clearing cache).

All the more reason to scrap this approach entirely and move towards something like #32? 😉 But the `cache` API might work here, as you said. I'll try to play around later.

**Comment by kilburn** [comment]
> but maybe we were all using a node type that got created every build, regardless of cache (or something)
I don't know... in the demonstration project I built the `createNode` calls are made on every `gatsby develop` (it doesn't use the `touchNode` api) yet the problem persists. Maybe it is some recent change/optimization in gatsby core?

I am now trying to make sense of gatsby's type definition APIs and I must confess it just doesn't click in my mind. I think I'll dream of resolvers, definitions, @link and whatnot tonight 😕

**Comment by kilburn** [comment]
In any case, I must say that #32 fixes both issues and seems to fit better with gatsby's general direction, so it is definitely an improvement for us :)

**Comment by wKovacs64** [comment]
I just pushed an update to #34, so we can at least get a 2.x version that works before considering the jump to v3 (#32). I tested it using your demo project, but you might want to try it yourself and confirm if you have time.
