### ISSUE TITLE
warn `createResolvers` passed resolvers for type `X` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers.

### ISSUE THREAD

**Issue by pmkemper** [graysonhicks/gatsby-plugin-remote-images#41]
I am using gatsby-source-wordpress and have an image URL here:
~~~~
query MyQuery {
  allWordpressPost {
    edges {
      node {
        featured_image_url
      }
    }
  }
}

~~~~

I am unclear about how to configure gatsby-plugin-remote-images to work with the above. 

I am probably doing something simple wrong, but so far I haven't been able to get it to work. 

No matter what I put in nodeType, I keep getting the warning:
```warn `createResolvers` passed resolvers for type `wordpressPost` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers.```

E.g. with a setup like:
~~~~
    {
      resolve: `gatsby-plugin-remote-images`,
      options: {
        nodeType: 'wordpressPost',
        imagePath: 'featured_image_url',
      },
    },
~~~~

How should I configure the plugin to work with gatsby-source-wordpress?

**Comment by fatihky** [comment]
Could you try `WordpressPost` as type, types start with an uppercase letter in general.

**Comment by pmkemper** [comment]
Same thing:
warn `createResolvers` passed resolvers for type `WordpressPost` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers.

I've tried all sorts of variations, but I always seem to get that warning.

**Comment by graysonhicks** [comment]
Shouldn't `gatsby-source-wordpress` already offer Gatsby Images of its images?  I'm not sure you need this plugin.

**Comment by AmruthPillai** [comment]
I'm getting this issue too, can someone help? I'm trying it on `gatsby-source-dev`.

This is the query structure:
```graphql
    {
      allDevArticles(
        sort: { fields: [article___published_at], order: DESC }
        limit: 6
      ) {
        edges {
          node {
            id
            article {
              title
              published_at(fromNow: true)
              positive_reactions_count
              description
              tags
              url
              social_image -> the remote image to be converted to gatsby-image
            }
          }
        }
      }
    }
```

This is the config:
```js
    {
      resolve: `gatsby-plugin-remote-images`,
      options: {
        nodeType: "devArticles",
        imagePath: "article.social_image",
      },
    },
```

But I get the same error that OP is noticing:
> warn `createResolvers` passed resolvers for type `devArticles` that doesn't exist in the schema.

**Comment by sheedy** [comment]
I get the same error with a default install of either version `1.07`, `2.0.0`,  or `2.1.0` of this plugin and Gatsby `2.20.29`.

> `createResolvers` passed resolvers for type `myNodes` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers.

**Comment by graysonhicks** [comment]
@AmruthPillai What version of the plugin are you using?
@sheedy What is your data source?  Is it a GraphQL endpoint?

**Comment by AmruthPillai** [comment]
@graysonhicks I was using the latest version 2.1.0.

**Comment by anindha** [comment]
I am having the same issue but sourcing from [Unsplash random](https://source.unsplash.com/user/erondu/1000x1000).

**Comment by anindha** [comment]
As a workaround I added to my `gatsby-node.js`:
```js
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)

exports.sourceNodes = async ({ actions, store, cache, createNodeId }) => {
  const { createNode } = actions;
  
  await createRemoteFileNode({
    // The source url of the remote file
    url: `https://source.unsplash.com/user/erondu/4000x4000`,
    cache,
    createNode,
    createNodeId,
    name: "random-unsplash",
    ext: ".jpg",
  })
}
```

**Comment by graysonhicks** [comment]
@AmruthPillai Have you tried with 1.0.7?

**Comment by sheedy** [comment]
@graysonhicks it was just a regular remote file like `https://example.com/example.png`

**Comment by graysonhicks** [comment]
Yes @sheedy , I meant the source as in the node source for that type of node.

**Comment by sheedy** [comment]
Ha, sorry! 🤦 IIRC it was `allMDX`. Is that what you mean?

**Comment by graysonhicks** [comment]
I believe this is related to #39 after attempting some work on it tonight.  Successfully implementing the `createTypes` API should clear both of these issues.

**Comment by EdgarNigel** [comment]
Probably you found a solution by now. 

If not, I was able to get remote images to work with gatsby-image. I tried `gatsby-plugin-remote-images` as well but couldn't get it to work. What did the job for me was creating a resolver for my remote API  (my remote cms source in`gatsby-source-graphql`, I use Webiny CMS) like so: 

In`gatsby-config.js`:
```
plugins: [
       {
		resolve: 'gatsby-source-filesystem',
		options: {
			name: 'images',
			path: '${__dirname}/src/images',
		},
         },
	{
		resolve: 'gatsby-source-graphql',
		options: {
		  typeName: "Webiny",
		  fieldName: "webinyHeadlessCms",
		  url: "https://XXXXXXXXXXX.cloudfront.net/cms/read/production",
		  headers: {
			authorization: "XXXXXXXXXXXXXXXXXXXX"
		  },
		  refetchInterval: 60,
		},
	},
  ],
```

And my `gatsby-node.js`:
```
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)

exports.createResolvers = ({actions,cache,createNodeId,createResolvers,store,reporter,}) => {
	const { createNode } = actions
	createResolvers({
		Webiny_BlogPost: {
			imageFile: {
				type: `File`,
				resolve(source, args, context, info) {
					return createRemoteFileNode({
						url: source.headerImage,
						store,
						cache,
						createNode,
						createNodeId,
						reporter,
					})
				},
			},
		},
	})
}
```

Now I can query images to use with gatsby-image now like so:
```
export const query = graphql`{
	webinyHeadlessCms {
	  	listBlogPosts {
			data {
				headerImage
				imageFile {
					childImageSharp {
					  	fluid (quality: 100, maxWidth: 1920) {
							...GatsbyImageSharpFluid_withWebp
						}
					}
				}
			}
		}
	}
}`
```

It is important to really understand the GraphQL Schema of your remote API. Have a look at it in GraphiQL. In my case the resolver creates a new node named `imageFile` at `Webiny_BlogPost`. In general this should be done at `typeName_SchemaType`, where the part before the underscore is your `typeName` defined in `gatsby-source-graphql` and the part after the underscore is the schema type within that source, you want to create your image (File) node in. 
When you query it, keep in mind, that you need to query the node with the remote image url as well (in my case `headerImage`) to make it work.

**Comment by jamesdefant** [comment]
@EdgarNigel - Could you please clarify a couple things as to how you got this working.

1) What does a regular call to this GraphQL api look like, so that it is clear which are new, arbitrary names and which are inherent to the API?

2) Do you not get this same error `warn 'createResolvers' passed resolvers for type 'API_IMAGES' that doesn't exist in the schema...` if you don't implement `createTypes` in gatsby-node.js?

3) Is Webiny_BlogPost the type that is defined in your API?

4) Is imageFile a new arbitrary name for this field?

**Comment by kater-mult** [comment]
I'm getting this error too on my Drupal/gatsby installation. Is the fix to use createTypes somewhere in my implementation?

**Comment by graysonhicks** [comment]
Yes, you could do something like defined here: https://www.gatsbyjs.com/docs/schema-customization/#fixing-field-types

**Comment by michal-wrzosek** [comment]
I had this error when using `gatsby-source-mongodb` plugin. In my case, the GraphQL for data coming from mongodb was `allMongodbDatabaseNameCollectionName`. Initially, I used `MongodbDatabaseNameCollectionName` as a `nodeType`. This caused the error `createResolvers passed resolvers for type X that doesn't exist in the schema`. Changing `nodeType` to `mongodbDatabaseNameCollectionName` fixed the problem (small letter in front).
