### ISSUE TITLE
`onCreateNode` doesn't trigger

### ISSUE THREAD

**Issue by denzo** [graysonhicks/gatsby-plugin-remote-images#45]
I'm using `gatsby-source-firestore` to get my data which contains remote image urls.

The above plugin creates nodes once the data is received
https://github.com/taessina/gatsby-source-firestore/blob/master/gatsby-node.js#L39

However, the `onCreateNode` in this plugin is not triggered for the nodes created by `gatsby-source-firestore`
https://github.com/graysonhicks/gatsby-plugin-remote-images/blob/develop/src/gatsby-node.js#L4

I was wondering if there is a workaround.

**Comment by graysonhicks** [comment]
Hm, the `onCreateNode` hook should work for nodes created anywhere.  Do you have a codepen or repo for reproducing?

**Comment by denzo** [comment]
Thanks for the quick reply @graysonhicks 

I have setup a public repo to reproduce https://github.com/denzo/gatsby-firestore-remote-image

1. https://github.com/denzo/gatsby-firestore-remote-image/blob/master/gatsby-node.js#L14
2. https://github.com/denzo/gatsby-firestore-remote-image/blob/master/src/templates/book-template.js#L20

**Comment by graysonhicks** [comment]
I notice you are trying to use the array `nodes[]` functionality.  Can you try using version `1.0.7`?

**Comment by denzo** [comment]
I just tried and it doesn't succeed with the query using the `1.0.7` version.

The `result.data = undefined` from here https://github.com/denzo/gatsby-firestore-remote-image/blob/master/gatsby-node.js#L14

**Comment by denzo** [comment]
@graysonhicks I was wondering if you had any suspicions what might be the cause of the issue to point me in a direction where I could investigate further.

**Comment by graysonhicks** [comment]
@denzo I have tried to recreate with a CodeSandbox of your repo (https://codesandbox.io/s/hopeful-lichterman-p8euj?file=/gatsby-config.js) but I get the error: 

`Cannot query field "allBook" on type "Query"`

I am thinking that might be an auth thing where I am missing a secret key or something.

As for the plugin, my next guess would be to double check the `imagePath` config.  I noticed you have `nodes[]` there but I don't think that is what you mean based on looking at your `gatsby-node`.  Can you try just `photoUrl`?  The `[]` notation is only for when there are multiple _images_ not multiple nodes.

**Comment by denzo** [comment]
@graysonhicks apologies, I had to disable the secret key included in the public repo after a few days of not hearing from you.

Your suggestion produced the desired results. Thanks so much!

I misunderstood that the `imagePath` is relative to the node 🙃

**Comment by graysonhicks** [comment]
Glad it's working! @denzo
