### ISSUE TITLE
Clarity on `localImage` availability

### ISSUE THREAD

**Issue by denzo** [graysonhicks/gatsby-plugin-remote-images#47]
I am using this awesome plugin successfully using a graphql query for a page:
```export const query = graphql`...```

However, when I use the same query (`localImage` specified) in `gatsby-node.js` inside `exports.createPages` it breaks the query. Note: I create pages dynamically using a template.

I'm having a difficulty creating a mental model of when `localImage` is available.

Also, what are my options to have `localImage` available in my template?

**Comment by graysonhicks** [comment]
@denzo This has to do with how Gatsby handles data from plugins.  I believe that any changes to the schema will not be available in `gatsby-node`.  In your template, you should have the same kind of template query shown in the docs here: https://www.gatsbyjs.org/tutorial/part-seven/.  Typically you only query very little in `gatsby-node` (like an id or a slug) and pass that in through context.  Then you should be able to query that node and have access to the `localImage`.
