### ISSUE TITLE
CLI does not properly report download progress

### ISSUE THREAD

**Issue by polarathene** [graysonhicks/gatsby-plugin-remote-images#48]
I raised the issue on the main Gatsby repo, they've since identified [the issue being due to this plugin](https://github.com/gatsbyjs/gatsby/issues/25041#issuecomment-648708426).

The linked issue comment provides feedback on what needs to be fixed. The reporter needs to be utilized.

**Comment by graysonhicks** [comment]
@polarathene Thanks!  This looks like a great thing to fix.

**Comment by graysonhicks** [comment]
@polarathene Should be fixed by this PR.

https://github.com/graysonhicks/gatsby-plugin-remote-images/pull/50

Will release it soon, thanks again!

**Comment by polarathene** [comment]
@graysonhicks awesome! Thanks for putting that together :grinning:

**Comment by graysonhicks** [comment]
Released with v2.2.0
