### ISSUE TITLE
Help accessing remote images with gatsby-image

### ISSUE THREAD

**Issue by sethxd** [graysonhicks/gatsby-plugin-remote-images#5]
Hey there,

I've managed to get this working but I'm struggling to write the graphql query to access these images. I'm using Ghost as the CMS and trying to optimize the featured images for posts, at least to start with. I'd like to do it for all images but I have no idea how to approach that.

My gatsby-config looks like this:

```
{
            resolve: `gatsby-plugin-remote-images`,
            options: {
                nodeType: `GhostPost`,
                imagePath: `feature_image`,
                name: `headerImage`,
            },
        }
```

And navigating GraphQL in the browser I can see the GhostPost property feature_image is being correctly grabbed and used for headerImage:

```
{
  "data": {
    "allGhostPost": {
      "edges": [
        {
          "node": {
            "headerImage": {
              "publicURL": "/static/5---4RfxFDK-95749338e4aa41c059ed5608126bc5a4.png",
              "childImageSharp": {
                "id": "3ac7b766-fb4e-5103-9620-0a1ee357dcb2"
              }
            }
          }
        },
        {
          "node": {
            "headerImage": {
              "publicURL": "/static/photo-1520792252957-84c5b4498e16-03cd2bc55f01346646a9006556095c12.jpg",
              "childImageSharp": {
                "id": "f974af44-20e2-5c00-8cc0-039bff297fe4"
              }
            }
          }
        }
      ]
    }
  }
}
```

I'm just lost trying to format the graphql query so I can use this in an Img component in the page. My post.js file already has a query:

```
export const postQuery = graphql`
    query($slug: String!) {
        ghostPost(slug: { eq: $slug }) {
            ...GhostPostFields
        }
    }
`
```
Do I add it to that one somehow, or make another? Any guidance would be greatly appreciated.

**Comment by graysonhicks** [comment]
Hi @sethxd !  Do you know what fields the `...GhostPostFields` fragment is defined to get?

**Comment by MikeBroders** [comment]
hey,

if you have this already...

` "headerImage": {
              "publicURL": "/static/photo-1520792252957-84c5b4498e16-03cd2bc55f01346646a9006556095c12.jpg",
              "childImageSharp": {
                "id": "f974af44-20e2-5c00-8cc0-039bff297fe4"
              }
            }`

given you have stored a node of the query in a variable called "node",  then you can easily use the image-data with gatsby-image like this :

`<Img fluid={node.headerImage.childImageSharp.fluid} />`

hope that fits your needs...

**Comment by graysonhicks** [comment]
Closing this since not related to plugin.
