### ISSUE TITLE
Workaround with gatsby-source-graphql

### ISSUE THREAD

**Issue by joeynimu** [graysonhicks/gatsby-plugin-remote-images#55]
Hi,

I know you said that it's [not possible at the moment for this plugin to work with `gatsby-source-plugin`](https://github.com/graysonhicks/gatsby-plugin-remote-images#gatsby-source-graphql) but is there a workaround for this? 

Thanks!

**Comment by graysonhicks** [comment]
Hi @joeynimu , I honestly have not tried it with the GraphQL source plugin in a while.  Have you tried it locally?  Would love to know what the errors are.  As far as I know it is still a blocker.  I believe there are some major changes coming for that plugin that may allow for a fix in the future.

**Comment by graysonhicks** [comment]
Reading this issue again for the first time in a while, it certainly looks doable. https://github.com/gatsbyjs/gatsby/issues/8404.

Gonna close this to keep the conversation in #7
