### ISSUE TITLE
Option to rename downloaded images

### ISSUE THREAD

**Issue by teddybradford** [graysonhicks/gatsby-plugin-remote-images#69]
Is there a way to rename downloaded images?

For example, given a remote image URL of `https://example.com/foobar-v3-483x500-copy.jpg` I would like to download the image and rename the file, e.g., `thumbnail.jpg`.

In other words, I'd like to have all downloaded images in a filename format such as: `thumbnail.[ext]`.

**Comment by graysonhicks** [comment]
I think this is blocked by a limitation of `createRemoteFileNode`, which already parses the file name.  PRs welcome though with ideas.

https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/#createremotefilenode
