### ISSUE TITLE
Gatsby 4

### ISSUE THREAD

**Issue by IstoraMandiri** [graysonhicks/gatsby-plugin-remote-images#71]
Currently this plugin will not install on Gatsby v4 without forcing.

After forcing an install, a basic test case seems to work, so perhaps it just needs `peerDependencies` updates and a version bump. 

```
npm install gatsby-plugin-remote-images --force
```

**Comment by graysonhicks** [comment]
Solved by #72 released with 3.2.0.  Thanks!
