### ISSUE TITLE
array of external url

### ISSUE THREAD

**Issue by cheuk3** [graysonhicks/gatsby-plugin-remote-images#9]
hi, i would like to ask if the plugin support if my node field contain an array of external url string

Thanks

**Comment by graysonhicks** [comment]
Hi @cheuk3! Not at the moment, but it has been asked before (https://github.com/graysonhicks/gatsby-plugin-remote-images/issues/8) and I would happily review a PR if you have one.  It is at the top of my list of things to add when I have time.

**Comment by graysonhicks** [comment]
This has been solved in #13 .  See updated README for using the nested array notation.
