### ISSUE TITLE
Old gatsby-source-filesystem throwing some errors

### ISSUE THREAD

**Issue by alexej-d** [graysonhicks/gatsby-plugin-remote-images#90]
Hi! Any chance you might update the dependency on gatsby-source-filesystem to a newer version (^4.0.0)? The version you use unfortunately throws several errors with specific slow servers. I have build a rudimentary case where I used your version and version 4.22.0 of gatsby-source-filesystem and only the older failed.

It seems the use of `fetchRemoteFile` from an old gatsby-core-utils is to blame for that.

**Comment by graysonhicks** [comment]
Thanks @alexej-d !  This should be resolved in `3.5.0` now.
